name: npm release

on:
  push:
    tags:
      - "*"
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/

      - name: npm test
        run: |
          npm install
          npm run lint --if-present
          npm test --if-present
        env:
          CI: true

      - run: npm run build --if-present
      
      - run: node overwrite_package_json.js

      - run: rm -rf node_modules

      - run: npm install

      - run: npm shrinkwrap

      - name: npm auth
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: npm auth & publish
        run: npm publish --access public
